version: '3.9'
services:
  postgres:
    container_name: airflow-quick-postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    networks:
      - airflow_quick_net


# (not docker0) for this dockercompose services (change subnet if you have network conflict)
networks:
  airflow_quick_net:
    ipam:
      config:
        - subnet: 112.18.0.0/16