version: '3.9'
services:
  postgres:
    container_name: airflow-quick-postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    networks:
      - airflow_quick_net

  airflow-quick-srv:
    container_name: airflow-quick
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: dev_image
      # args:
        # ARG_NAME: ARG_VALUE
    # The Standalone command will initialise the database, make a user,
    # and start all components for you.
    command: ["airflow", "standalone"]
    restart: always
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      - postgres
    env_file:
      - airflow-env-variables.env
    ports:
      - "81:8080"
    volumes:
      - type: bind
        source: ../runtime/dags
        target: /opt/airflow/dags
      - type: bind
        source: ../runtime/logs
        target: /opt/airflow/logs
      - type: bind
        source: ../runtime/plugins
        target: /opt/airflow/plugins
      - type: bind
        source: ../runtime/tests
        target: /opt/airflow/tests
    networks:
      - airflow_quick_net

  airflow-pycharm-interpreter:
    container_name: airflow-quick-interpreter
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: dev_image
    # entrypoint: ["/pycharm-interpreter.sh"]
    # start a trigger process to allow webservice run along side with pycharm interpreter
    # https://airflow.apache.org/docs/apache-airflow/stable/concepts/deferring.html#using-deferrable-operators
    command: ["triggerer"]
    restart: "no"
    depends_on:
      postgres:
        condition: service_started
      airflow-quick-srv:
        condition: service_healthy
    env_file:
      - airflow-env-variables.env
    volumes:
      - type: bind
        source: ../runtime/dags
        target: /opt/airflow/dags
      - type: bind
        source: ../runtime/logs
        target: /opt/airflow/logs
      - type: bind
        source: ../runtime/plugins
        target: /opt/airflow/plugins
      - type: bind
        source: ../runtime/tests
        target: /opt/airflow/tests
    networks:
      - airflow_quick_net

# (not docker0) for this dockercompose services (change subnet if you have network conflict)
networks:
  airflow_quick_net:
    ipam:
      config:
        - subnet: 112.18.0.0/16